# Generated by Django 2.1 on 2018-02-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapreprocessor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=255, null=True)),
                ('branch_location', models.CharField(max_length=255, null=True)),
                ('food_type', models.CharField(max_length=255, null=True)),
                ('item_type', models.CharField(max_length=255, null=True)),
                ('item_unit', models.CharField(max_length=255, null=True)),
                ('item_base', models.IntegerField(null=True)),
                ('item_packet', models.IntegerField(null=True)),
                ('restaurant_initial_stock_quantity', models.FloatField(null=True)),
                ('restaurant_stock_remaining_now', models.FloatField(null=True)),
                ('price_per_quantity', models.FloatField(null=True)),
                ('restaurant_stock_created_at', models.DateTimeField(null=True)),
                ('vendor', models.CharField(max_length=255, null=True)),
                ('vendor_contact_number', models.CharField(max_length=255, null=True)),
                ('quantity', models.FloatField(null=True)),
                ('restaurant_stock_allocated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'stocks',
            },
        ),
    ]
