# Generated by Django 2.1 on 2018-02-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapreprocessor', '0002_stocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=255, null=True)),
                ('branch_location', models.CharField(max_length=255, null=True)),
                ('food_type', models.CharField(max_length=255, null=True)),
                ('amount', models.FloatField(null=True)),
                ('sold_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'sales',
            },
        ),
    ]
